# Generated by Django 2.1.7 on 2019-03-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languages', models.IntegerField(choices=[(1, 'python'), (2, 'C'), (3, 'Java'), (4, 'C++')], default=1)),
                ('content', models.TextField()),
            ],
        ),
    ]
