# Generated by Django 2.2.1 on 2019-06-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0002_auto_20190313_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coding',
            name='content',
            field=models.TextField(max_length=10000),
        ),
    ]
